version: "3.6"
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: always
    restart: unless-stopped
    volumes:
      - /home/choppy/Files/AppData/Config/broadlinkmanager:/opt/broadlinkmanager/data

