version: "3"
volumes:
  postgres: {}
  
services:
  homechart:
    container_name: homechart
    depends_on:
      - postgres
    environment:
      HOMECHART_POSTGRESQL_HOSTNAME: postgres
      HOMECHART_POSTGRESQL_PASSWORD: postgres
      HOMECHART_POSTGRESQL_USERNAME: postgres
    image: candiddev/homechart:latest
    ports:
      - "3030:3000"
    restart: always
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/postgres:/var/lib/postgresql/data
