version: "2"

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/mariadb/matomo:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - ./db.env

  app:
    image: matomo
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/matomo/config:/var/www/html/config
      - /portainer/Files/AppData/Config/matomo/logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env
    ports:
      - 8282:80 #changed from default 8080

volumes:
  db:
  matomo: